type Owner = {
  ownerFirstName: string;
  ownerMiddleName: string;
  ownerLastName: string;
  ownerStateID: string;
  ownerSSN: string;
  ownerPercentOwnership: number;
  ownerTitle: string;
  ownerBirthday: string;
  ownerEmail: string;
  ownerAddress: string;
  ownerCity: string;
  ownerZip: string;
  ownerPhone: string;
};

type AllDataForm = {
  corpLegalFedTaxId: string;
  corpLegalName: string;
  corpLegalAddress: string;
  corpLegalCity: string;
  corpLegalState: string;
  corpLegalZip: string;
  corpLegalPhone: string;
  corpLegalEmail: string;
  yearsInBusiness: number;
  aditionalDetailsLocations: number;
  aditionalDetailsWebsite: string;
  aditionalDetailsMailing: string;
  merchDBAName: string;
  merchAddress: string;
  merchCity: string;
  merchState: string;
  merchZip: string;
  merchPhone: string;
  controllerOfficerIsOwner: string;
  controllerOfficerFirstName: string;
  controllerOfficerMiddleName: string;
  controllerOfficerLastName: string;
  controllerOfficerDob: string;
  controllerOfficerTitle: string;
  controllerOfficerEmail: string;
  controllerOfficerAddress: string;
  controllerOfficerCity: string;
  controllerOfficerZip: string;
  controllerOfficerHomePhone: string;
  controllerOfficerLicenseNumber: string;
  controllerOfficerLicenseNumberExpires: string;

  businessProfileOwnershipType: string;
  businessProfileBusinessType: string;
  businessProfileGoodsServices: string;
  businessProfileBankName: string;
  businessProfileBusinessCheckingAccount: string;
  businessProfileBusinessCheckRouting: string;
  businessProfileBusinessCheckRoutingCheck: string;
  businessProfileBusinessCheckingAccountCheck: string;
  businessProfileDriverLicenseImage: string;
  businessProfileVoidedCheckImage: string;
  owners: Owner[];
  controllerOfficerOfficerIsOwner: string;
  salesProfileCurrentlyMCVISA: string;
  salesProfileRetailChipSwipe: string;
  salesProfileCurrentProcessor: string;
  salesProfileAvgTicket: string;
  salesProfileMaxTicket: string;
  salesProfileMonthlyVolume: string;
  salesProfileMailPhone: string;
  salesProfileInternetPerc: string;
  salesProfileB2BPerc: string;
  salesProfileB2CPerc: string;
  salesProfileB2GPerc: string;
};

export default AllDataForm;
