export const formDataBusiness = {
    businessName: "",
    businessLegalName: "",
    businessRegistrationNumber: "",
    businessOwnershipType: "",
    businessTaxId: "",
    businessGiin: "",
    businessIncorporationDate: "",
    businessCompanyWebsiteUrl: "",
    businessDbaName: "",
    businessDbaWebsiteUrl: "",
    businessDynamicDescriptor: "",
    businessDescription: "",
    businessCustomerServicePhone: "",
    businessCustomerServiceEmail: "",
    businessFax: "",
    businessAgreement: "",
    businessCustomField1: "",
    businessCustomField2: "",
    businessCustomField3: "",
    businessPhoneNumber: "",
    businessEmailAddressForNotices: "",
    businessNumberOfLocations: 0,
    businessNumberOfOutlets: 0,
  }