export const formDataBusiness = {
  businessName: "",
  businessLegalName: "",
  businessRegistrationNumber: "",
  businessOwnershipType: "",
  businessTaxId: "",
  businessGiin: "",
  businessIncorporationDate: "",
  businessBusinessAddress: {
    street: "",
    country: "",
    stateCode: "",
    apartment: "",
    city: "",
    zip: "",
  },
  businessCorporateAddress: {
    street: "",
    country: "",
    stateCode: "",
    apartment: "",
    city: "",
    zip: "",
  },
  businessCompanyWebsiteUrl: "",
  businessDbaName: "",
  businessDbaWebsiteUrl: "",
  businessDynamicDescriptor: "",
  businessDescription: "",
  businessCustomerServicePhone: "",
  businessCustomerServiceEmail: "",
  businessFax: "",
  businessAgreement: "",
  businessCustomField1: "",
  businessCustomField2: "",
  businessCustomField3: "",
  businessPhoneNumber: "",
  businessEmailAddressForNotices: "",
  businessNumberOfLocations: 0,
  businessNumberOfOutlets: 0,
  businessDetailsDocumentsRegistrationCertificate: "",
  businessDetailsDocumentsProofOfAddress: "",
  businessDetailsDocumentsArticleOfIncorporation: "",
  businessDetailsDocumentsCustomDocument1: "",
  businessDetailsDocumentsCustomDocument2: "",
  businessDetailsDocumentsCustomDocument3: "",

}